/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvisorPicker: typeof import('./src/components/AdvisorPicker.vue')['default']
    CommandPalette: typeof import('./src/components/CommandPalette.vue')['default']
    ContextStrip: typeof import('./src/components/ContextStrip.vue')['default']
    DilutionPath: typeof import('./src/components/DilutionPath.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    EquityBenchmark: typeof import('./src/components/EquityBenchmark.vue')['default']
    ExitSlider: typeof import('./src/components/ExitSlider.vue')['default']
    FootballField: typeof import('./src/components/FootballField.vue')['default']
    FrappeChart: typeof import('./src/components/FrappeChart.vue')['default']
    GrowthWaterfall: typeof import('./src/components/GrowthWaterfall.vue')['default']
    MixBreakdown: typeof import('./src/components/MixBreakdown.vue')['default']
    NumIn: typeof import('./src/components/NumIn.vue')['default']
    PackageEditor: typeof import('./src/components/PackageEditor.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    PoolAllocation: typeof import('./src/components/PoolAllocation.vue')['default']
    ReviewPanel: typeof import('./src/components/ReviewPanel.vue')['default']
    RosterIdentity: typeof import('./src/components/roster/RosterIdentity.vue')['default']
    RosterRow: typeof import('./src/components/roster/RosterRow.vue')['default']
    RosterTable: typeof import('./src/components/roster/RosterTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenarioTable: typeof import('./src/components/ScenarioTable.vue')['default']
    Term: typeof import('./src/components/Term.vue')['default']
    TierBadge: typeof import('./src/components/roster/TierBadge.vue')['default']
    TrajectoryView: typeof import('./src/components/TrajectoryView.vue')['default']
    UpsideCurve: typeof import('./src/components/UpsideCurve.vue')['default']
    VestingTimeline: typeof import('./src/components/VestingTimeline.vue')['default']
  }
}
