/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FrappeChart: typeof import('./src/components/FrappeChart.vue')['default']
    NumIn: typeof import('./src/components/NumIn.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PoolAllocation: typeof import('./src/components/PoolAllocation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
